name: Flask CI/CD Pipeline

on:
  workflow_dispatch:  # Enable manual trigger from the GitHub interface
    inputs:
      dockerhub_username:
        description: 'DockerHub Username'
        required: true
        default: 'ravinadh'
      dockerhub_password:
        description: 'DockerHub Password'
        required: true
        default: 'Cloud@12345'
      ansible_playbook_path:
        description: 'Path to the Ansible Playbook'
        required: true
        default: '/home/ubuntu/ansible-playbooks/deploy_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd  myproject
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ravinadh
          password: Cloud@12345

    - name: Build Docker Image
      uses: docker/setup-buildx-action@v2

    - name: Push Docker Image to DockerHub
      uses: docker/build-push-action@v4
      with:
          context: .
          file: myproject/Dockerfile
          tags: ravinadh/testing:flask

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i $ANSIBLE_HOSTS_PATH $ANSIBLE_PLAYBOOK_PATH
      env:
        ANSIBLE_HOSTS_PATH: "/home/ubuntu/hosts.ini"
        ANSIBLE_PLAYBOOK_PATH: ${{ github.event.inputs.ansible_playbook_path }}
        DOCKERHUB_USERNAME: ${{ github.event.inputs.dockerhub_username }}
        DOCKERHUB_PASSWORD: ${{ github.event.inputs.dockerhub_password }}
