name: Flask CI/CD Pipeline

on:
  workflow_dispatch:  # Enable manual trigger from the GitHub interface
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd  myproject
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: bhanukadali1998
          password: Kbhanu1234@

    - name: Build Docker Image
      uses: docker/setup-buildx-action@v2

    - name: Push Docker Image to DockerHub
      uses: docker/build-push-action@v4
      with:
          context: myproject
          file: myproject/Dockerfile
          tags: bhanukadali1998/webapplication:flaskimage

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i myproject/hosts.ini  ansible-playbooks/deploy_docker.yml
